### ISSUE TITLE
Rewrite function to await

### ISSUE THREAD

**Issue by jenokizm** [yortus/asyncawait#16]
tell me how rewrite this function with the expectation?
```
    var titles = GetTitles();
    ///....
    function GetTitles() {
    var titles;
    connection.query('SELECT * FROM titles', function (err, rows) {
        titles = rows;
    });
     return titles;
}
```
I would like to wait for the result  C#
```
var titles = await GetTitles();
///....
function async GetTitles() { ///.... }

```

**Comment by yortus** [comment]
Does `connection.query` also return a promise? If not, you'll have to make a version that does return a promise first. I don't know what DB library you are using so I'll assume it doesn't return promises. `knex.js` returns Promises so if you can use that I recommend it, as the code will interoperate much more easily with async/await style.

Anyhow, if your `connection.query` method only takes callbacks, then do something like this first:

```javascript
// NB: if you are using iojs, Promise is already defined as a global
var Promise = require('bluebird');

function getTitles() {
    return new Promise(function (resolve, reject) {
        connection.query('SELECT * FROM titles', function (err, rows) {
            if (err) return reject(err);
            resolve(rows);
        });
    });
}
```

Then you can write some other async function that calls `getTitles` like this:

```javascript

var doStuffAsync = async (function () {
    ...
    var titles = await (getTitles());
    ...
    var result = someOtherFunc(titles);
    return result;
});
```

When called, `doStuffAsync` will return a promise of its result.


On the other hand, if `connection.query` returned a promise directly, you wouldn't need `getTitles` at all, you could just do:

```javascript
var doStuffAsync = async (function () {
    ...
    var titles = await (connection.query('SELECT * FROM titles'));
    ...
    var result = someOtherFunc(titles);
    return result;
});
```

**Comment by jenokizm** [comment]
Thanks! tomorrow, as will certainly try and describe the time.
ps its mysql connection https://www.npmjs.com/package/mysql

**Comment by yortus** [comment]
FYI, there are some promise-oriented wrappers for the `mysql` library:
* [`mysql-promise`](https://github.com/martinj/node-mysql-promise)
* [`promise-mysql`](https://github.com/lukeb-uk/node-promise-mysql)

I suggest using one of these, since they will work directly with async/await.

**Comment by jenokizm** [comment]
I get to set the old python. I liked more your way, but tell me if I can call a doStuffAsync func in addition? Why it again operates asynchronously, and I do not get the desired result (
![ashampoo_snap_2015 06 01_20h29m39s_002_](https://cloud.githubusercontent.com/assets/11296510/7919681/af57f954-08a2-11e5-9b63-ff79ed389e1b.png)

**Comment by yortus** [comment]
`doStuffAsync()` is an ordinary (but asynchronous) function that returns a promise. The promise instance is what you can see in your screenshot above.

You need to await the asynchronous function call to suspend the caller until the promise resolves - ie `titles = await (doStuffAsync())`.

It's important to understand that to use `await` you need to be inside the definition of another `async` function. That is because suspending a function requires some kind of coroutine support, which normal functions do not provide, hence the `async` wrapper function.

That means that your outermost layer of functionality (perhaps the API you expose to your module's consumers) would still expose promise-returning functions.

So if `doStuffAsync()` was some public method, consumers would use it like a normal promise-returning function, ie `doStuffAsync().then(function (result) { ... })`.

**Comment by yortus** [comment]
Closing this as there seems no further action to be taken. Feel free to open another issue if you have more questions.
