### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by jenokizm** [yortus/asyncawait#17]
Registry url: https://registry.npmjs.org/
Current Time: 28.05.2015 18:35:03
Last Refreshed: 14.05.2015 19:40:52
Number of Results: 157348
====Executing command 'npm install asyncawait --save '====

npm WARN package.json NodejsWebApp3@0.0.0 No repository field.
> fibers@1.0.5 install C:\Users\Jenok\Documents\Visual Studio 2013\Projects\NodejsWebApp3\NodejsWebApp3\node_modules\asyncawait\node_modules\fibers
> node ./build.js
child_process: customFds option is deprecated, use stdio instead.
C:\Users\Jenok\Documents\Visual Studio 2013\Projects\NodejsWebApp3\NodejsWebApp3\node_modules\asyncawait\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (rebuild --release ) 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\Jenok\Documents\Visual Studio 2013\Projects\NodejsWebApp3\NodejsWebApp3\node_modules\asyncawait\node_modules\fibers
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
Build failed
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "asyncawait" "--save"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Jenok\Documents\Visual Studio 2013\Projects\NodejsWebApp3\NodejsWebApp3\npm-debug.log

====npm command completed with exit code 1====

**Comment by yortus** [comment]
This is an error installing `node-fibers`. It is not an error with `asyncawait`.

`asyncawait` depends on `node-fibers` to provide its coroutines.

`node-fibers` is a binary module so it has a special compilation step. This step can be skipped if you use node version 0.10.x, because it bundles pre-built binaries for established node versions.

If you are using iojs or node 0.12.x, then read on.

Unfortunately, `node-fibers` is less actively maintained at the moment so it hasn't kept up with the latest node and iojs changes. It's still possible to install `node-fibers` on these newer versions, but requires doing the build step. This step is automatic, by relies on `node-gyp`, which requires python to be installed on your computer. The `node-fibers` or `node-gyp` READMEs should have more instructions.

For iojs even that is not enough. Many binary modules (such as `node-fibers`) keep breaking with the rapid iojs update cycle, because they compile against the underlying V8 version which is frequently updated in iojs, and its changing API breaks builds. `node-gyp` itself needs special steps to get working on iojs.

I can't give many more details than that but hopefully you get the idea:
* avoid iojs for now if you depend directly or indirectly on binary modules (such as `node-fibers`)
* if you are using node 0.12.x, try installing python first, then your problem should be fixed
* if the above fails, try using node 0.10.x and it should install without problems.

**Comment by alexeygritsenko** [comment]
ok. i install Python and Python Tools for Visual Studio, but new error:
# gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.
It looks like a joke on me, no desire even to reinstall the old version ... ((

**Comment by jenokizm** [comment]
ok. i install Python and Python Tools for Visual Studio, but new error:
> gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.

It looks like a joke on me, no desire even to reinstall the old version ... ((

**Comment by yortus** [comment]
FYI From the [`node-gyp`](https://github.com/TooTallNate/node-gyp) README:

> On Windows:
Python (v2.7.3 recommended, v3.x.x is not supported)
Make sure that you have a PYTHON environment variable, and it is set to drive:\path\to\python.exe not to a folder.

**Comment by yortus** [comment]
Also, no need for PTVS, only `node-gyp` needs python.
