### ISSUE TITLE
Can I use it in angular?

### ISSUE THREAD

**Issue by diegomesata** [yortus/asyncawait#19]
Can I use it in angular? How can I do it?

Thank you

**Comment by yortus** [comment]
Use can use it server-side (ie with node.js) but not client-side. That's because it uses a node-specific library called `node-fibers` to provide coroutine support, and browsers don't support this.

I don't use angular so I don't have any angular-specific advice to give. But there should be no problem using this in your server-side code regardless of which framework you use.
