### ISSUE TITLE
Asyncawait.d.ts link broken

### ISSUE THREAD

**Issue by ShMcK** [yortus/asyncawait#27]
The link in the README.md is broken. I believe the actual link was moved to [here](https://github.com/yortus/asyncawait/blob/master/src/types.d.ts). The typed file could also be made available on TSD for easy access.

**Comment by yortus** [comment]
Thanks @ShMcK for catching this.

I've removed the link in the README, since as of TS1.6 a separately distributable typings file (ie asyncawait.d.ts) is no longer needed.

For the same reason, there's no need to submit an `asyncawait.d.ts` file to DefinitelyTyped/TSD. The DT site (and TSD tool) should only deal with ambient typings for pure JavaScript libraries going forward.
