### ISSUE TITLE
Unhandled Exceptions/Errors inside async do not kill the server

### ISSUE THREAD

**Issue by Zaggen** [yortus/asyncawait#34]
It seems exceptions get logged and then swallowed by the async fn. So i can't apply the pattern of letting the server crash, because it swallows the exception. So neither `'uncaughtException'` or `'unhandledRejection'` get even fired.

So doing something like this
```
async(function() {
  new Promise(function(resolve, reject) {
    setTimeout((function() {
      reject(new Error("Lets die"));
    }), 15);
  });
})();
```
Or even this
```
async(function() {
  throw new Error("Die!!");
})();
```

Will log the error, but that's it, the server will keep running, and there is no way to catch the `'unhandledRejection'` event since it never fires.

error log example:
```
Possibly unhandled Error: Die!!
  at C:\myapp\api\controllers\traits\restfulTraits.coffee:42:19
  at tryBlock (C:\myapp\node_modules\asyncawait\src\async\fiberManager.js:39:33)
  at runInFiber (C:\myapp\node_modules\asyncawait\src\async\fiberManager.js:26:9)
.... more stacktrace
```
Is this the expected behavior, or is it a bug? When i use try catch everything works as expected, but i only use those to catch exceptions i know might happen, not to catch bugs, i want my server to crash when an error is not caught by anything and get at least one of process `'uncaughtException'` or `'unhandledRejection'` events to be fired.

I hope i made myself clear, if not let me know and i'll try to explain better, and if i'm doing something wrong, let me know that too. I'm getting this behavior inside sails.js controller methods (actions), so i must admit i haven't isolated the issue, but i can assume my examples are valid.

Thanks in advance

pst: I love this module :)

**Comment by yortus** [comment]
Hi @Zaggen,

Yes, your issue is clear. It's not a bug, but it's certainly due for an update/improvement.

The `unhandledRejection` event was added to Node [relatively recently (v1.4.1)](https://github.com/nodejs/node/blob/master/CHANGELOG.md#notable-changes-60). It is only triggered by native Promises whose rejection goes unhandled.

Node had neither native Promises nor `unhandledRejection` when I originally wrote `asyncawait`. I used the `bluebird` promise library instead. Up until now there has been little reason to switch to native promises, however I'd say your issue here might be a good reason to reconsider that.

Moving away from `bluebird` promises might adversely affect performance, so I think its worth investigating first whether node's `unhandledRejection` can be fired by an unhandled bluebird rejection.

I'll look into this when I have time. What I'll try is subscribing to [`bluebird`'s global `unhandledRejection` event](http://bluebirdjs.com/docs/api/error-management-configuration.html#global-rejection-events) and having that fire node's `unhandledRejection` event. If you feel like experimenting, maybe try that yourself and let me know if it works.

**Comment by Zaggen** [comment]
Hey @yortus , thanks for the fast response. You are right, this something relatively new in node for native promises. I've tested bluebird (2.9.30) and it supports this (as stated from v 2.7):

```
Promise = require('bluebird')
new Promise.reject(new Error('i should die now right?'))
```
Triggers the `unhandledRejection` event

I'm not sure how your module works internally, but since bluebird is already firing that event, is there something catching it in async/await? that prevents its propagation to the global event?, if that's the case, i guess there is no reason to manually trigger the native promise event if bluebird is already doing it.

I'll try checking into that as soon as i have time, can you point me out in the right direction in your module, so i might get there faster.

**Comment by yortus** [comment]
Hey @Zaggen,

OK, I've investigated this and had a few surprises.

Firstly, I added a unit test that shows that the `unhandledRejection` event *is fired* if an async function has an unhandled rejection. This surprised me as I thought the problem was that it was not firing. If you checkout the latest commit on the master branch, you can run [this new test](https://github.com/yortus/asyncawait/blob/master/test/async.ts#L109) for yourself.

Secondly, I checked the [node.js documentation regarding `unhandledRejection`](https://nodejs.org/api/process.html#process_event_unhandledrejection). It turns out that unlike unhandled exceptions, unhandled rejections do not crash the process. You can see this for yourself by executing a script like the following:

```js
setInterval(() => console.log('still running...'), 500);
var unhandled = new Error('unhandled');

// Uncaught exceptions DO crash the process by default
//throw unhandled;

// Uncaught rejections DO NOT crash the process by default
Promise.reject(unhandled);
```

So it looks like what you want is to add your own handler to crash the process on an unhandled rejection. I tried the following and it works (try adding it to the script above):

```js
process.on('unhandledRejection', er => {
    console.log('Unhandled Rejection: ' + er);
    console.log('Terminating process...');
    process.exit(1);
});
```

Does that adequately deal with this issue for you?

**Comment by Zaggen** [comment]
Hey @yortus i realized that yesterday, but my main issue remains (i've tested again with a `console.log` and `process.exit`), the event is not getting called, so i can't in turn call `process.exit()`. I'm going to run the new tests you've added to see if they work on my machine. If they are working for you then it might be an issue with the version i'm using? I'm running `0.7.4`, so let me check if by updating everything works, and if the unit test passes, then it must be something else in my app environment that is conflicting with it.

**Comment by Zaggen** [comment]
Ok indeed the issue is now fixed, the problem was the version of bluebird you had `2.10.0`, prior to the asyncawait v `1.0.2` from January, and since bluebird started supporting this from version `2.7` it was never going to work. So this issue is officially close then, if someone runs into the same problem its just a matter of updating the model. 

Thanks a lot for your assistance, i really appreciate that, and its cool that we have an extra unit test to make sure it works :)

pst: Should we change the title of the issue to `unhandledRejection` not getting fired?
