### ISSUE TITLE
Eslint

### ISSUE THREAD

**Issue by mateeyow** [yortus/asyncawait#37]
How can I enable asyncawait on eslint? `babel-eslint` doesn't seem to work.

**Comment by yortus** [comment]
Hi @mateeyow,

Sorry for the delay, I've been travelling.

Since I'm not an eslint user, would you mind explaining in a little more detail what you are wanting to do?

**Comment by akhileshk** [comment]
I am running into similar problem, this is the error I get "Parsing error: Unexpected token". Eslint is pointing to  parenthesis after await(some_method()). it is getting confuse with ES7 await call without any parenthesis.

**Comment by yortus** [comment]
`await` is not a reserved word inside function bodies, even in 'ES7', so it's strange that eslint would have a rule about it. Can it be switched off?

**Comment by akhileshk** [comment]
I am going to ask the question on eslint forum, I believe it's reporting error because it expect es7 style await as follow:
await someAsyncFunction()
   //rather than
await ( someAsyncFunction())

**Comment by yortus** [comment]
`await (someAsyncFunction())` would be a valid expression even with with ES async/await, so it's still unclear why there would be a parsing error.

**Comment by akhileshk** [comment]
here is the discussion thread at babel-eslint forum.
https://github.com/babel/babel-eslint/issues/319#issuecomment-224949676

**Comment by yortus** [comment]
Thanks @akhileshk, that comment you linked too isn't too helpful but I think I may have found your problem. It looks like you need to tell `babel-eslint` to parse your files in 'script' mode, not 'module' mode. The [configuration section in the README](https://github.com/babel/babel-eslint#configuration) states how to do that. Let me know if that helps.

To clear up some things in the comment:

> await is a reserved word in ES6 modules,

only at the module top-level (where the `import`/`export` declarations are), but not inside function bodies ([spec](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-future-reserved-words)). Babel is buggy to complain about `await` in function bodies.

> ES6 modules, which is what Babel expects all files to be.

babel supports both 'script' and 'module' parsing modes. I haven't seen your source code but I'm guessing since you are using `asyncawait` that you don't use a transpiler, so you are writing `var foo = require('foo')` rather than `import foo from 'foo'`. The latter format is what babel calls a 'module', since it's using ES6 module format. The former is the CommonJS format that node.js natively supports, this format is what babel calls a 'script'.

> The easiest solution to your problem would be to use real async functions instead of that module.

Perhaps. To use ES async/await today, you need a transpilation step in your project, which may be a factor in what's 'easiest'. In the long term, when no transpiler is needed, it's probably a slam-dunk to just use ES async functions. Even then asyncawait can do a number of things ES async functions can't, like awaiting more than one stack level deep, which is sometimes useful in asynchronous functional programming. YMMV.

**Comment by rsshilli** [comment]
This makes this really hard to use.  Basically we can't use this library in Node 6 then, since await is a reserved keyword and it doesn't support export/import ES6 modules.  Right?

**Comment by yortus** [comment]
@rsshilli I would recommend switching to native async/await when you can. You could also try importing the `await` function using a non-reserved name, eg `_await` or `AWAIT` or whatever.

**Comment by rsshilli** [comment]
I solved my problem that I was working on at the time using Promise.reduce() to basically run a group of promises in sequence.

If only AWS Lambda supported Node 8 where await is natively supported then my life would be a lot easier!  Oh well.  

Thank you for the response. I appreciate it.

**Comment by Seikho** [comment]
@rsshilli I use async/await on AWS Lambda by transpiling using TypeScript. You could do the same with Babel.
