### ISSUE TITLE
asyncawait require-ing a higher fibers than exist? 

### ISSUE THREAD

**Issue by vanchisel** [yortus/asyncawait#41]
Can anyone give a reason getting the message below. Fibers built from npm install only produces 
win32-x64-v8-5.0, not win32-x64-v8-5.1?

I'm running electron v1.2.0; node v6.2.0; npm v3.8.9; chromedriver 2.21

C:\Users\Thomas\electron\eqs\node_modules\fibers\fibers.js:16 Uncaught Error: `C:\Users\Thomas\electron\eqs\node_modules\fibers\bin\win32-x64-v8-5.1\fibers.node` is missing. Try reinstalling `node-fibers`?

**Comment by yortus** [comment]
Hi @vanchisel, 

Are you still having this problem?

If you've recently updated your node version, then any native modules (such as `node-fibers`) previously installed in `node_modules` may stop working due to new Node API incompatibilities. The usual solution is to delete the `node_modules` directory entirely, then do `npm install` again. Does that work for you?

**Comment by vanchisel** [comment]
Hello @yortus,

Thank you for responding. I deleted `node_modules` just now and it didn't work: "...win32-ia32-v8-5.1\fibers.node` is missing." The problem seems with building 'node fibers'. I'd love to use `asyncawait`. I abandoned `nwjs` for electron because `nw-gyp` couldn't build `node sqlite3`+ other issues. Electron only has problem with `asyncawait`/`fibers`.

Right now I'm using Bluebird but would love another help because I can see some Promise.then() aren't flowing correctly.

**Comment by Zeppelin15** [comment]
Hi, I am having a similar issue and am also using electron,
 get a "node_modules\fibers\bin\win32-x64-v8-5.2\fibers.node" is missing error message. 
npm installing fibers only gives up to win32-x64-v8-5.0

**Comment by yortus** [comment]
I don't know much about electron but I found [this page](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md) in the Electron docs. Could it be relevant?

**Comment by Derek20** [comment]
Hi, I am also now running into this issue while using electron. 

I tried that link you referred to @yortus but still no luck and I'm running out of ideas.

Any other ideas? Thanks

**Comment by null4bl3** [comment]
Issue confirmed on part as well:

> Error: `/home/xxxx/xxxxxxxxx/server/node_modules/fibers/bin/linux-x64-v8-5.1/fibers.node` is missing. Try reinstalling `node-fibers`?

Issue is most likely on the part of [node-fibers](https://github.com/laverdet/node-fibers), as i can't seem to install it on its own due to build errors.

**Comment by yortus** [comment]
Since this problem isn't caused by or solvable by asyncawait, I'm going to close this. The [fibers repo](https://github.com/laverdet/node-fibers) may be a more useful place to further discuss this. Note there are several issues there about this already. Unfortunately it seems to be a not-supported scenario.
