### ISSUE TITLE
How to use asyncawait in the browser?

### ISSUE THREAD

**Issue by GarouDan** [yortus/asyncawait#42]
If we are not in node-like environment and we would like to have the asyncawait library running just in the browser, how can we do it?

For example, to the code below, how can we put it to work?

```
<!DOCTYPE html>
<html>
    <head>
        <script type='text/javascript' src='asyncawait.bundle.js'></script>
        <script type='text/javascript'>
            async function slow() {
                return new Promise(function(resolve, reject) {
                  setTimeout(function() {
                      console.log("slow finished");
                      resolve();
                  }, 3000);
                });
            }

            function fast() {
                console.log("fast");
            }

            async function run() {
                await slow();
                fast();
            }

            run();
        </script>
    </head>
    <body>
    </body>
</html>
```

**Comment by yortus** [comment]
Hi @GarouDan, 

`asyncawait` (i.e. this library) is strictly node-only because it relies on the native node module `node-fibers`.

As you probably know, `async/await` (not linked to this library except by common inspiration/origins) is now a [stage-3 proposal](https://tc39.github.io/ecmascript-asyncawait/) for integration into the JavaScript language itself, but it still has little current browser support (MS Edge supports it).

To use `async/await` in browsers today, your best bet is probably to use [Babel](http://babeljs.io/docs/plugins/transform-async-to-generator/) to transpile your code to equivalent ES5. Async functions get transpiled into equivalent code that uses ES5 generators, which most browsers do support. I believe there is even a way to transpile to equivalent ES3 although the transformation is complex and you will no longer recognise your source code, but it should run in all browsers.

I'm not sure if Babel can help with script blocks embedded in a html file like your example above. It would be best to separate the JavaScript into its own file(s).

Closing as there is nothing actionable for asyncawait here, but feel free to comment/reopen if you have more questions.
