### ISSUE TITLE
Error handling with Mocha/other unit testing libraries doesn't work as expected

### ISSUE THREAD

**Issue by markasoftware** [yortus/asyncawait#43]
When an error occurs in an `async` function, instead of throwing an error it just logs a message to the console (or that's what it seems like to me at least). Mocha doesn't register this error, and just waits until the timeout of 2000ms instead of failing immediately like it would in a non-async function. I think there needs to be some way to have it throw errors like it would traditionally so it works with Mocha and other similar unit testing frameworks instead of what it does currently.

**Comment by yortus** [comment]
Hi @markasoftware,

> When an error occurs in an async function, instead of throwing an error it just logs a message to the console

If an error is thrown (and left unhandled) inside an `async` function, then what happens is that the promise returned by the `async` function gets rejected. This is the correct behaviour for an async function. It can't throw into its caller like a synchronous function does, because by the time the error occurs, the caller and it's associated call stack may be long gone (having run on an earlier tick of the event loop).

BTW `asyncawait` does not log errors to the console, so something else in your environment must be doing that, probably mocha.

Try writing your tests like this:

```js
var async = require('asyncawait/async');
var await = require('asyncawait/await');

describe('some test suite', () => {
    it('some test', async.cps(() => {
        // asynchronous test logic here...
        await (...)
        expect(...)
        assert(...)
        // etc...
    });
});
```

`async.cps` creates an async function that accepts a node-style callback rather than returning a promise (cps = continuation passing style). This exactly matches mocha's expectations for an asyncronous test function, which it expects to be of the form `(done) => { /* test body which eventually calls done(err) to throw or done() to return */ }`

Please let me know how that goes and if you need further help.

**Comment by markasoftware** [comment]
Thank you for the quick response, my issue is now resolved. I didn't understand that async functions returned a promise and all that because I was too lazy to read the readme. Now that I read up a bit I figured out how to use it properly, without a `done` callback, and it is working beautifully.
