### ISSUE TITLE
Use with ES6 classes

### ISSUE THREAD

**Issue by DomVinyard** [yortus/asyncawait#48]
The following pattern doesn't work. Is there any supported way to assign async methods to an ES6 class instance?

```javascript
class API {
  constructor(options)  { }
  async test() {
      let test = await this.get('test')
      console.log(test)
  }
}
```

**Comment by yortus** [comment]
You couldn't do it neatly within the ES6 class syntax, because `async` and `await` are just ordinary functions in this library, whereas they are keywords in the ES async/await proposal.

Your options are:

- use a transpiler like TypeScript or Babel and use ES class and async/await syntax (then you don't need this lib).
- use this library but write your classes the old-fashioned way (define constructor function, then add async methods to constructor's prototype).

**Comment by mrcybermac** [comment]
Why not just add the async function to the class prototype?  Seems easy and direct:

```const async = require('asyncawait/async')
const await = require('asyncawait/await')

class MyClass {
    firstMethod() {
        console.log('firstMethod')
    }
}

MyClass.prototype.secondMethod = async(function () {console.log(await('secondMethod'))})

const myClassInstance = new MyClass()

console.log(myClassInstance.firstMethod())

myClassInstance.secondMethod().then(function (data) { console.log(data)})```

Output is:

```
firstMethod
secondMethod
```

Please let me know if I'm missing something important here.
