### ISSUE TITLE
Upgrade fibers package for nodejs 10.x or 12.x

### ISSUE THREAD

**Issue by iTechDhaval** [yortus/asyncawait#74]
I looked at fibers README and they have mentioned different versions of fibers for different nodejs versions.

* NodeJS 10.x or 12.x --> `fibers@4`
* NodeJS v8.x --> `fibers@3`
* NodeJS v6.x --> `fibers@2`
* NodeJs v4.x --> `fibers@1`

What do you suggest best possible way to accommodate this dependancy restriction for `asyncawait` package?

**Comment by yortus** [comment]
I think just make a PR upgrading the `fibers` dependency to v4, and bumping `asyncawait`'s version to `3.0.0`.

If in future anybody needs something to work with node 8.x (which I doubt since nobody has raised it so far), then there's still the possibility to release a version `2.0.0` that uses fibers@3.

**Comment by iTechDhaval** [comment]
Perfect. I will do it.

**Comment by nitin-synapptra** [comment]
Is there a release planned for this? 

I tried updating to node 12.x but failed due to this fibers issue. Works fine on node 10.x currently.

**Comment by iTechDhaval** [comment]
@nitin-synapptra i had to generate pull request. I will do it asap.

**Comment by iTechDhaval** [comment]
@yortus can you please merge #75 to support this task?

**Comment by yortus** [comment]
I've just merged #75 and published the new version of this package to npm. Thanks again @iTechDhaval.
