### ISSUE TITLE
 Await behavior in non Async function or normal function

### ISSUE THREAD

**Issue by bkvaiude** [yortus/asyncawait#77]
Hello,

I looking for help to understand the following piece of code

If you notice `sayMyName` function is a normal function without the `async` keyword
and it uses the `await` keyword against two promise statements

As per my understanding `await` can be used in `async` functions only.

Can someone share more insights on this behavior?

```
var async = require('asyncawait/async');
var await = require('asyncawait/await');
var rp = require('request-promise-native');

var myPromise = new Promise(function(myResolve, myReject) {
    myResolve("Namaste!");
  });

function sayMyName(){
    console.log("there")
    let greet = await(myPromise)
    let googlePage = await(rp('http://www.google.com'))
    console.log(greet)
    console.log(googlePage)
}
(async( ()=>{console.log("Hello"); sayMyName()}))()
```

**Comment by yortus** [comment]
Hi @bkvaiude, this library is different from the native async/await syntax in JS (it's a userland package that predates the native syntax). You may want to consider using native async/await syntax unless you have a specialised need for this library.

To answer your question:

> As per my understanding await can be used in async functions only.

This is true for native async functions, because they are 'shallow' coroutines. However, async functions created by this library are 'deep' coroutines, and can be suspended (ie awaited) at any stack depth, so your example above works fine. I wouldn't use this all over the place, but it can be handy, eg for map/filter/reduce callbacks inside an async function, or some other specialised use cases.
